- src/components/Login/SignUp/CreateAccount/CreateAccount.js
+ Made more requirements for usernames: can't use  ".", "#", "$", "[", or "]" - This is for firebase
+ changed database schema - username is the top level name, (cant use above chars so email wont work)
+  When a user creates an account their profile is made and uploaded to the database.
> Feature-profile creation

- src/App.js
- src/components/Banner/Banner.css
- src/components/Banner/Banner.js
> Sign-up prompt banner

- src/App.js
- src/components/AddListing/AddListing.js
- src/components/Banner/Banner.css
- src/containers/Home/Home.css
- src/containers/Home/Home.js
- src/containers/Profile/Profile.js
- src/hoc/Layout/RemoveMe.txt
- src/store/reducer.js
Created Home container -- use dummy data from profile
Make banner only shown on home page
> Feature home tile

- src/components/FilterMenu/CategoryMenu/CategoryMenu.css
- src/components/FilterMenu/CategoryMenu/CategoryMenu.js
- src/components/FilterMenu/FilterMenu.css
- src/components/FilterMenu/FilterMenu.js
- src/components/FilterMenu/ZipCodeMenu/ZipCodeMenu.css
- src/components/FilterMenu/ZipCodeMenu/ZipCodeMenu.js
- src/containers/Home/Home.js
- added category menu
- added filter menu
- added some styles
- lacks backend implementation right now
> Feature category menu

- src/components/FilterMenu/CategoryMenu/CategoryMenu.js
- src/components/FilterMenu/FilterMenu.js
- src/components/FilterMenu/ZipCodeMenu/ZipCodeMenu.js
- src/containers/Home/Home.js
added skeleton to the filter menu and made it show up on homepage
> added skeleton to filtermenu code.

- src/components/FilterMenu/CategoryMenu/CategoryMenu.js
- src/components/FilterMenu/FilterMenu.js
- src/components/FilterMenu/ZipCodeMenu/ZipCodeMenu.js
+ Completed filtering - it doesn't actually display the listings yet as I need to talk to whoever made that part
+ Does not do most recent / non recent as this hasn't been implemented in our listings as well or database.
> Access database and query through / filter out specific listings.

- package-lock.json
- src/components/FilterMenu/FilterMenu.js
- src/components/ListingHome/ListingHome.js
- src/containers/Home/Home.js
+ Added visual updating of listings to home screen when selecting a category or a zipcode.
NOTE:
There are some bugs / differences we can sort out easily though:
1. I need to add a callback or .then() somewhere to fix the loading of filtered listings.
For example, when you pick a category the first time, it doesn't load in time, but if you move off / go back to it (because at the moment its an on change event) then it will work.
2. The way in which I am grabbing listings I believe may be a little different then you, but this can be fixed easily.
3. At the moment I set it so only 6 listings are being shown. API Call grabs all listings though. I will make this more efficient soon, when / if we decide to have a component for pages / customization of how many listings can be on the screen at …
> Feature filter menu

- src/App.js
- src/components/Banner/Banner.js
- src/components/Header/Header.css
- src/components/Inventory/Inventory.css
- src/components/ItemDetails/ItemDetails.css
- src/components/ItemDetails/ItemDetails.js
- src/components/ListingHome/ListingHome.js
- src/components/ListingHome/ListingitemHome/ListingItemHome.js
- src/components/UI/Button/Button.css
- src/components/UserProfile/UserProfile.css
- src/components/UserProfile/UserProfile.js
- src/containers/Profile/Profile.css
- src/containers/Profile/Profile.js
The merge has the click handler for the home listings that brings you to the details page.
> Profile pic + Item Details

- .idea/misc.xml
- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/Inventory/Inventory.js
- src/components/Listing/Listing.js
- src/containers/Profile/Profile.js
Should work as expected, beware small remaining bug when entering text do not go back to a box you have put the edited text into again., or it will overwrite your changes to the default placeholder values.
> Inventory Edit fix

- .idea/misc.xml
- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/Inventory/Inventory.js
- src/components/Listing/Listing.js
- src/containers/Profile/Profile.js
messed up master again gg Shane
> Revert "Inventory Edit fix"

- src/components/Header/Header.js
- src/components/Inventory/Inventory.css
- src/containers/Profile/Profile.css
- src/containers/Profile/Profile.js
Just some minimal changes to the profile page. Nothing important
> Style profile page

- .idea/misc.xml
- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/Inventory/Inventory.js
- src/components/Listing/Listing.js
- src/containers/Profile/Profile.js
> Revert "Revert "Inventory Edit fix""

- .idea/misc.xml
- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/Inventory/Inventory.js
- src/components/Listing/Listing.js
- src/containers/Profile/Profile.js
> Revert "Revert "Revert "Inventory Edit fix"""

- src/components/AddListing/AddListingForm/AddListingForm.js
- src/containers/Profile/Profile.js
more fixes required to get addITem to work, had to remove several reverse calls because each one changed the ordering of the array from that maintained on the server, and broke the updating
> Fix add item

- src/components/ItemDetails/ItemDetails.css
- src/components/ItemDetails/ItemDetails.js
- src/components/ItemDetails/WinningBidButton/WinningBidButton.css
- src/components/ItemDetails/WinningBidButton/WinningBidButton.js
+ added winner button to
+ code ready to conditionally render for owner.
> Feature winnerbutton

- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/FilterMenu/CategoryMenu/CategoryMenu.js
- src/components/Inventory/Inventory.js
- src/components/Listing/Listing.js
- src/containers/Home/Home.js
- src/containers/Profile/Profile.js
> Feature separate auction bid

- src/App.js
- src/components/ItemDetails/BidItems/BidItem/BidItem.css
- src/components/ItemDetails/BidItems/BidItem/BidItem.js
- src/components/ItemDetails/BidItems/BidItems.css
- src/components/ItemDetails/BidItems/BidItems.js
- src/components/ItemDetails/ItemDetails.css
- src/components/ItemDetails/ItemDetails.js
> Bid items list for item

- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/ItemDetails/ItemDetails.js
- src/components/Listing/Listing.js
- src/components/Listing/ListingItem/ListingItem.js
- src/containers/Profile/Profile.js
+ Did all the work to delete auctions and bids from the database. got correct data passed through just need small code to talk to DB.
> Feauture delete button

- src/App.js
- src/components/ItemDetails/BidItems/BidItem/BidItem.js
- src/components/ItemDetails/BidItems/BidItems.js
- src/components/ItemDetails/ItemDetails.js
- src/components/Listing/ListingItem/ListingItem.js
- src/components/UserProfile/ProfileLogs/ProfileLogs.css
- src/components/UserProfile/ProfileLogs/ProfileLogs.js
+ Created winning button to conditionally render for the owner.
+ When clicked, it deletes the auction and all items that are selected. everything in DB should be working
+ logs these items into the /userItems/log folder
+ created localhost:3000/logs - which at the moment consoles all the logs of the logged in user.
> Winning button + notification  / logs

- src/components/AddListing/AddListingForm/AddListingForm.js
- src/components/UserProfile/UserProfile.css
- src/components/UserProfile/UserProfile.js
- src/containers/Profile/Profile.js
Zip codes are no longer hardcoded. Added default user picture. Able to upload a new picture. "picture" is now a property under userInfo, and it has the image url for the profile picture.
> Add profile pic

- src/components/ItemDetails/ItemDetails.js
- src/components/ListingHome/ListingHome.js
Tiny change. Zip code is now available in the item details page, ready to be passed in to the map component
> get item zip code to details page

- src/containers/Profile/Profile.css
- src/containers/Profile/Profile.js
text no longer overlaps if you have bid items but no auction items
> Cosmetic fixes on profile page

- src/components/ItemDetails/BidItems/BidItems.js
- src/components/ItemDetails/ItemDetails.js
+ created subfolders for log
- aWin - when auction owner selects a winner
- bWin - when the bidder wins
- lose - when another bidder in the auction is not selected after auction is done.
+ (hopefully) correctly sending these logs to everyone
+ added date to the log so we know time/day of when this occurs.
- CURRENTLY NOT IMPLEMENTED - but may be smarter to make this to a "object type thing" where we set each log item to have a field for "time", e.t.c.... shouldn't be too hard to modify though.
> UPDATE LOG FEATURE

- src/components/Header/NavigationItems/NavigationItems.js
- src/components/UI/EmailBox/EmailBox.css
- src/components/UI/EmailBox/EmailBox.js
- src/components/UserProfile/ProfileLogs/ProfileLogs.css
- src/components/UserProfile/ProfileLogs/ProfileLogs.js
Bell in navigation links to log page. Log page layout is set up. The e-mail box tiles are ready, one is hard coded so you can easily see it. Props info in EmailBox.js
> Log navigation
